version: 0.0
os: linux
hooks:
  BeforeInstall:
    - location: scripts/preinstall.sh
      timeout: 300
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/verify.sh
      timeout: 300